--- #YAML:1.0
name: Array-AsHash
version: 0.31
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "Treat arrays as a hashes, even if you need references for keys."
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
