---
name: Array-AsHash
version: 0.02
author:
  - Curtis <ovid@cpan.org>
abstract: ~
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Std: 0
  Clone: 0.18
  Scalar::Util: 1.14
  Test::More: 0
provides:
  Array::AsHash:
    file: lib/Array/AsHash.pm
    version: 0.02
generated_by: Module::Build version 0.2702
